name = "manabi-local"
type = "javascript"
# The ID of the domain to deploying to
account_id = "aae2fcb83b85225f854e7fc4c1620a25"
compatibility_date = "2021-11-30"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[env.dev]
workers_dev = true
name = "manabi-dev"

[env.production]
zone_id = "72d8a4ba2d528bc3300227072b3c0816"
name = "manabi"
route = "*naoriku.dev/*"
